global MIN_TRAIN_LENGTH
MIN_TRAIN_LENGTH = 5
global MIN_TRANSMISSION_INTERVAL
MIN_TRANSMISSION_INTERVAL = 0.001
global DT_CONSECUTIVE
DT_CONSECUTIVE = 6
global BOUNDARY_PCT
global BOUNDARY_PDT


def update_globals(mtl, mti, dtc, bpct, bpdt):
    MIN_TRAIN_LENGTH = mtl
    MIN_TRANSMISSION_INTERVAL = mti
    DT_CONSECUTIVE = dtc
    BOUNDARY_PCT = bpct
    BOUNDARY_PDT = bpdt